server:
 port: 8761 # 8761是eureka server的默认端口

eureka:
# server:
#  enable-self-preservation: false
 client:
  service-url:
   defaultZone: http://127.0.0.1:${server.port}/eureka/ #eureka server的应用注册地址
  register-with-eureka: false
  fetch-registry: false

spring:
 application:
  name: eureka-demo
