server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/ #eureka server的应用注册地址
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: eureka-project
